SELECT * FROM "DBA"."TABLAS_PARAMETRIZADAS"
SELECT * FROM DBA.HISTO_HUELLAS

   SELECT TP_CAMPO  FROM DBA.TABLAS_PARAMETRIZADAS WHERE TP_COMPANIA = 1 AND TP_TABLA = 'HUELLAS_FIGERS' AND TP_ESTADO=1; .



-------------------------------------------------DE LATBLA HUELLAS-------------------------------------------------;
INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('HUELLAS_FIGERS','TABLA PARA HUELLAS DIGITALES','HUE_OBSERVACION','OBSERVACION DE LA HUELLA',0,1)

INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('HUELLAS_FIGERS','TABLA PARA HUELLAS DIGITALES','HUE_ID','IDENTIFICADOR UNICO',1,1)

INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('HUELLAS_FIGERS','TABLA PARA HUELLAS DIGITALES','HUE_CODIGO','CODIGO DE COOP O DEF ',0,1)

INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('HUELLAS_FIGERS','TABLA PARA HUELLAS DIGITALES','HUE_IDENTIDAD','IDENTIDAD DEL COOP',1,1)

INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('HUELLAS_FIGERS','TABLA PARA HUELLAS DIGITALES','HUE_TIPO_PER','TIPO DE LA PERSONA (COOP Y DETALLA FIRMAS)',0,1)

--DE LA TABLA ROLES
INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('ROL_HUELLA','ROLES PARA EL USO DEL ADDON','ID_ROLHUE','ID DEL ROL',1,1)
INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('ROL_HUELLA','ROLES PARA EL USO DEL ADDON','NOMBRE_ROLHUE','NOMBRE DEL ROL',0,1)
--DEL USUARIOS
INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('USUARIOS_HUELLAS','USUARIOS PARA USO DE ADDON','ID_USR','ID DEL USUARIO',1,1)
INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('USUARIOS_HUELLAS','USUARIOS PARA USO DE ADDON','ID_ROLUSR','ID DEL ROL',0,1)
INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('USUARIOS_HUELLAS','USUARIOS PARA USO DE ADDON','NOMBRE_USR','NOMBRE DEL USR',0,1)
INSERT INTO "DBA"."TABLAS_PARAMETRIZADAS" ("TP_TABLA","TP_DESCRIPCION_TABLA","TP_CAMPO","TP_DESCRIPCION_CAMPO","TP_PRIMARY_KEY","TP_ESTADO")
 VALUES('USUARIOS_HUELLAS','USUARIOS PARA USO DE ADDON','TOKEN_ID','TOKEN DE ACCESO',0,1)


select coop_nombre from dba.COOPERATIVISTAS



CREATE  TABLE #nombre_tabla_temporal (
    columna1 VARCHAR (250)
  
);

create global temporary TABLE  TempGlobarTable(
    campo VARCHAR (500) 
) on commit preserve rows;


SELECT * 
FROM sys.
WHERE name = '#nombre_temporal'
AND type = 'T';  -- 'T' es el tipo de objeto para tablas


DROP TABLE TempGlobarTable

SELECT * FROM  sys.SYSTABLE;


SELECT * FROM #nombre_tabla_temporal



select  column_name from sys.SYSCOLUMN where table_id=(SELECT table_id FROM SYS.SYSTABLE WHERE table_name = 'HUELLAS_FIGERS') 
          SELECT * FROM DBA.TABLAS_PARAMETRIZADAS WHERE TP_COMPANIA = 1 AND TP_TABLA = 'HUELLAS_FIGERS' AND TP_ESTADO=1;  





begin
IF ('ID_ROLHUE' in ('gas','ID_ROLHUE')) THEN 
 select 'insertado';
end if;
end


SELECT  xp_read_file('C:\SISC\Addons\DDigital\info.txt')
SELECT CAST(xp_read_file('C:\SISC\Addons\info.txt') AS VARCHAR);

