SELECT 
  fxc.FXC_PARENTEZCO,
  CASE 
    WHEN FXC.FXC_TIPO_PERSONA = 'COOP' THEN COOP.COOP_NOMBRE
    WHEN FXC.FXC_TIPO_PERSONA = 'DEF' THEN DF.DEF_NOMBRE
  END AS NOMBRE,
  CASE 
    WHEN FXC.FXC_TIPO_PERSONA = 'COOP' THEN COOP.COOP_IDENTIDAD
    WHEN FXC.FXC_TIPO_PERSONA = 'DEF' THEN DF.DEF_IDENTIDAD
  END AS IDENTIDAD,
isnull(firma, 'N/A', firma) as firma
FROM 
  "DBA"."FIRMAS_X_CUENTA" FXC
LEFT JOIN DBA.COOPERATIVISTAS COOP ON FXC.FXC_TIPO_PERSONA = 'COOP' AND COOP.COOP_IDENTIDAD = FXC.FXC_IDENTIDAD
LEFT JOIN DBA.Detalle_Firmas DF ON FXC.FXC_TIPO_PERSONA = 'DEF' AND DF.DEF_SEC = FXC.FXC_IDEN_DEF
LEFT JOIN (
    SELECT 'Firma 1' as firma, Codigo_Cta_Aho as CTA, FIRMA1_AHO_IDEN AS IDENTIDAD FROM  dba.Firmas_Ahorro 
    WHERE Codigo_Cta_Aho = 10078369
    UNION
    SELECT 'Firma 2' as firma, Codigo_Cta_Aho as CTA, FIRMA2_AHO_IDEN AS IDENTIDAD FROM  dba.Firmas_Ahorro 
    WHERE Codigo_Cta_Aho = 10078369
    UNION 
    SELECT 'Firma 3' as firma, Codigo_Cta_Aho as CTA, FIRMA3_AHO_IDEN AS IDENTIDAD FROM  dba.Firmas_Ahorro 
    WHERE Codigo_Cta_Aho = 10078369
    UNION 
    SELECT 'Firma 4' as firma, Codigo_Cta_Aho as CTA, FIRMA4_AHO_IDEN AS IDENTIDAD FROM  dba.Firmas_Ahorro 
    WHERE Codigo_Cta_Aho = 10078369
) AS FF ON FF.CTA = FXC.FXC_CTA_AHO AND FF.IDENTIDAD = FXC.FXC_IDENTIDAD 

WHERE FXC.FXC_CTA_AHO = 10078369 and FF.IDENTIDAD <>'N/A' order by firma asc;